############################################################
# +------------------------------------------------------+ #
# |                  STAFF LOCATIONS                     | #
# +------------------------------------------------------+ #
############################################################
staff-locations-module:
    enabled: true
    icons: []