############################################################
# +------------------------------------------------------+ #
# |                  ALT ACCOUNT DETECTION               | #
# +------------------------------------------------------+ #
############################################################

alt-detect-module:
    enabled: false
    same-ip-required: false