############################################################
# +------------------------------------------------------+ #
# |                       Reports                        | #
# +------------------------------------------------------+ #
############################################################

# No permission required for regular users, requires "permissions.report" permission for moderator commands.
reports-module:
    chatchannels:
        enabled: false
        open-on: IN_PROGRESS
        close-on: REJECTED;RESOLVED;DELETED

    # Whether or not the plugin will use "/report" features.
    enabled: true

    # The sound that is played to staff when someone is reported.
    # Set to "NONE" to disable.
    sound: ENTITY_EXPERIENCE_ORB_PICKUP

    # The cooldown, in seconds, for using "/report".
    # This is disabled for players with the "permissions.report" permission.
    cooldown: 10

    # Whether or not the player that reported another player will be visible in GUIs.
    show-reporter: true

    # Whether or not a staff member must provide a reason when resolving/rejecting a report
    closing-reason-enabled: true

    # Types of reports. When configured the reporter will see a UI where he must choose the type
    report-types: [ ]
    fixed-reason: false
    fixed-reason-culprit: false
    reasons: [ ]

    reporter-notifications:
        # The reporter will be notified the moment he comes online that he has reports OPEN or IN_PROGRESS
        notify-on-join: true
        # Enable status change notifications. Whenever a staff member changes the status to one of the specified statuses, the reporter will be notified (if he is online).
        # Statuses must be semi-colon separated
        status-change-notifications: IN_PROGRESS;RESOLVED;REJECTED
    # command hooks
    accept-commands: [ ]
    reject-commands: [ ]
    reopen-commands: [ ]
    resolve-commands: [ ]