main: net.shortninja.staffplus.core.StaffPlusPlus
name: StaffPlusPlus
version: ${project.version}
description: The ultimate moderation plugin!
author: Shortninja,Qball,Garagepoort
softdepend: [PacketListenerApi, PlaceholderAPI, LuckPerms, Vault, GroupManager, AuthMe]
api-version: 1.13