# Staff++ | Made with love by Shortninja and continued by Qball - Revisited by Garagepoort

# If you're having trouble with item type names, refer to here: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
# All item slots are how they "should be", meaning the first slot of an inventory will be one. Maximum is 36.

############################################################
# +------------------------------------------------------+ #
# |                       General                        | #
# +------------------------------------------------------+ #
############################################################

# The name of the server. This can be anything you want but it must be unique and once chosen it shouldn't change anymore.
server-name: "MyUniqueServerName"
# The name of the main world. Meaning the world folder name which contains the player data files.
main-world: "world"
# The format in which all dates will be displayed inside the GUIs.
timestamp-format: 'dd/MM/yyyy-HH:mm:ss'

# The language file that will be referred to for messages.
# Current available languages are: lang_en, lang_sv, lang_de, lang_nl, lang_es, lang_hr, lang_no, and lang_fr.
# If you would like to translate Staff++, please message me on Spigot!
lang: "lang_en"

# Chooses the authentication provider. Default "noop", no authentication will be done.
# AuthMe is supported. When the provider is authMe, Staff++ will enforce that the user is authenticated through AuthMe before being able to execute the commands.
authentication:
    provider: noop

# Commands that staff will not be allowed to use at all.
# Must have "permissions.block" permission to take effect.
# Leave blank to disable.
blocked-commands: "/example1, /example2, /example3"

# The default color of glass for the side of GUIs. Just a cosmetic thing that staff members can change.
glass-color: 0

# The title of the glass color chooser GUI.
glass-title: "&bChoose GUI glass color"

# Enable offline player mode
# report-bypass & warn-bypass does not work for offline players
offline-players-mode: true

# When enabled commands will have autocompletion for offline players.
# Disable this if you notice the plugin having a slow startup time.
# This could happen if you have a very large player base.
offline-player-cache: true


############################################################
# +------------------------------------------------------+ #
# |                  SESSION synchronization             | #
# +------------------------------------------------------+ #
############################################################
# Module to enable synchronizing specific staff session features.
server-sync-module:
    vanish-sync: false
    staffmode-sync: false
    ban-sync: ''
    report-sync: ''
    warning-sync: ''
    mute-sync: ''
    kick-sync: ''
    investigation-sync: ''
    notes-sync: ''
    staff-location-sync: ''

############################################################
# +------------------------------------------------------+ #
# |                       Locations                        | #
# +------------------------------------------------------+ #
############################################################
# Used to predefine certain locations in the world which can be used in other commands
# Type in the location identifier and location using format: x;y;z;worldname
# ex. config
# locations:
#     - name: spawn
#       coordinates: 14;45;62;world
# ex. /freeze myplayer -Tspawn
# This will freeze the player and teleport him to spawn location.
locations: []

############################################################
# +------------------------------------------------------+ #
# |                         Chat                         | #
# +------------------------------------------------------+ #
############################################################

# Requires "permissions.chat" permission.
chat-module:
    # Whether or not the plugin will use "/chat" features.
    enabled: true

    # The amount of lines that will be sent when "/chat clear" is executed.
    lines: 100

    # The cooldown, in seconds, for chatting when the chat is slowed.
    # Bypass permission is "chat-slow".
    slow: 5

    # Whenever one of these words/phrases is detected in a chat message, the actions defined will be executed
    # In addition a notification can be sent to staff members through the alerts-system or the discord integration plugin.
    detection:
        phrase-groups:
            -   phrases:
                    - admin
                    - mod
                actions: [ ]

############################################################
# +------------------------------------------------------+ #
# |                      MUTING                       | #
# +------------------------------------------------------+ #
############################################################

joinmessages-module:
    # Whether or not the plugin will use "/mute player" features.
    enabled: true
    messages:
        -   permission: 'staff.joinmessages.staff'
            message: '&6[Staff] &4%player% &7joined the server'
            weight: 1

command-detection:
    enabled: true
    command-groups:
        -   commands:
                - op
                - deop
                - lp
            actions: [ ]

############################################################
# +------------------------------------------------------+ #
# |                  STAFF LOCATIONS                     | #
# +------------------------------------------------------+ #
############################################################
staff-locations-module:
    enabled: true
    icons: []

############################################################
# +------------------------------------------------------+ #
# |                   WEBUI                     | #
# +------------------------------------------------------+ #
############################################################

# Allow all investigation functionalities
webui-module:
    enabled: false
    host: https://web.staffplusplus.org
    role: MEMBER
    application-key: 'EXAMPLE_KEY'


############################################################
# +------------------------------------------------------+ #
# |                      Storage                         | #
# +------------------------------------------------------+ #
############################################################

# How will the plugin still Data
storage:
    #Type is how it will store either a sqlite or mysql
    type: 'sqlite'
    migrations-table-name: 'migrations'
    mysql:
        host: 'localhost'
        user: 'root'
        database: 'root'
        password: 'mypass'
        port: 3306
        max-pool-size: 5
        ssl-enabled: false

############################################################
# +------------------------------------------------------+ #
# |                       Advanced                       | #
# +------------------------------------------------------+ #
############################################################

# The declared version of this configuration file, used for configuration file changes.
# Do NOT change this unless you know what you're doing (hint: just don't change it).
config-version: 6205

# The interval in seconds at which calculations, like freeze checking, will be performed.
# The higher this is, the less lag there will be.
clock: 10

# The animation packets that will be listened for and cancelled for total vanished players.
# Each packet is separated by a comma.
animation-packets: PacketPlayOutBlockBreakAnimation, PacketPlayOutBlockAction

# The sound names that will be listened for and cancelled for total vanished players.
# Each name is separated by a comma.
sound-names: random.chestopen, random.chestclosed

#Used to turn on or off metrics please keep true
metrics: true

# you're done with the config file, shit waddup