############################################################
# +------------------------------------------------------+ #
# |                        Alerts                        | #
# +------------------------------------------------------+ #
############################################################

# Requires "permissions.notify" permission.
alerts-module:
    # Whether or not staff will be notified when a user changes their name.
    name-notify: true
    name-notify-console: false
    name-notify-bungee: ''

    # Whether or not staff will be notified when they are mentioned.
    mention-notify: true
    mention-notify-console: false
    mention-notify-bungee: ''

    # Whether or not staff will be notified when the chat module detect phrases.
    chat-phrase-detection: true
    chat-phrase-detection-console: false
    chat-phrase-detection-bungee: ''

    # Whether or not staff will be notified when the command-detection gets triggered.
    command-detection: true
    command-detection-console: false

    # Whether or not staff will be notified when the command-detection gets triggered.
    blacklist-detection: true
    blacklist-detection-console: false
    blacklist-notify-bungee: ''

    # The sound that is played to staff when notified.
    sound: ENTITY_EXPERIENCE_ORB_PICKUP

    # Notifies staff when a player mines blocks listed in "blocks".
    xray-alerts:
        # Whether or not this module is enabled.
        enabled: true
        console: false
        notify-bungee: ''
        # Block type that, when mined, will invoke an alert.
        blocks: SPAWNER, EMERALD_ORE, DIAMOND_ORE, GOLD_ORE, IRON_ORE, COAL_ORE, LAPIS_ORE, REDSTONE_ORE

    alt-detect-notify:
        enabled: true
        console: false
        # Trust levels for which an alert should be triggered
        # POSITIVE;FAIRLY_POSITIVE;POSSIBLE;NOT_LIKELY
        trust-levels: FAIRLY_POSITIVE;POSITIVE