############################################################
# +------------------------------------------------------+ #
# |                      Freezing                        | #
# +------------------------------------------------------+ #
############################################################
freeze-module:
    enabled: true
    chatchannels:
        enabled: false
    chat: false
    damage: false
    blindness: false
    timer: 5
    sound: ENTITY_EXPERIENCE_ORB_PICKUP
    prompt: false
    prompt-title: '&bFrozen'
    logout-commands: ban %player%
    title-message-enabled: true
    chat-message-enabled: true
    # Commands that are allowed when a player is frozen
    allowed-commands: [ ]
    # command hooks for freeze/unfreeze
    freeze-commands: [ ]
    unfreeze-commands: [ ]