############################################################
# +------------------------------------------------------+ #
# |                      INVENTORIES                     | #
# +------------------------------------------------------+ #
############################################################

# Interaction with inventories
examine-module:
    enabled: true
    gui:
        title: "&bExamine inventory"
        info-line:
            food: 1
            ip-address: 2
            gamemode: 3
            infractions: 4
            location: 5
            notes: 6
            freeze: 7
            warn: 8

############################################################
# +------------------------------------------------------+ #
# |                      ENDERCHESTS                     | #
# +------------------------------------------------------+ #
############################################################

# Interaction with enderchests
enderchest-module:
    enabled: true