############################################################
# +------------------------------------------------------+ #
# |                    Blacklist                         | #
# +------------------------------------------------------+ #
############################################################
# All word blacklist options.
# Leave any of the lists below blank to disable them!
blacklist-module:
    # Whether or not the blacklist will be enabled.
    enabled: false

    censor-chat: true
    censor-signs: true
    censor-anvil: true
    censor-book: true
    # Whether or not messages that have censored words in them will be hoverable.
    # This means you will be able to hover over a chat message to see an uncensored message if you have the "permissions.blacklist" permission.
    # This may not work well with other chat plugins!
    hoverable: false

    # The character that will replace blocked word characters.
    character: "*"

    # Whether or not messages that have merged blocked words will be detected.
    # So if you block the word "ass", it will also block "asshole" or "dickass".
    # May cause issues with legal words like "bypass"! Fix is below.
    merging: true

    # All words that will be censored.
    # Separate words with commas.
    words: fuck, shit, ass, bitch, dick, cock, piss, cunt, fag, faggot, slut, nigger, nigga

    # All characters that will be censored.
    # These are merely characters that will be detected anywhere in messages.
    characters: 卐, 卍

    # All domain levels that will be censored.
    # This can prevent users from sending links in chat.
    # This will only check the end of words which have detected periods!
    domains: com, net, org

    # All strings that will be detected as periods in messages. Of course characters like "." and "," are detected by default.
    # This will work in coordination with "domains".
    # For example, it can detect "mineplex()com" as "mineplex.com".
    periods: (), (dot),

    # All words that will be allowed to be typed no matter what.
    # This helps quite a bit if you have "merging" enabled.
    # I recommend using http://www.morewords.com/contains/[word]/!
    allowed: bypass, assembly, assassin, compass, assume, assault, asset, assort
