# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: MasterBuild

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]
    workflow_dispatch:
        branches: [ master ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up JDK 1.16
                uses: actions/setup-java@v1
                with:
                    java-version: 1.16
            -   uses: s4u/maven-settings-action@v2.4.0
                with:
                    mirrors: '[{"id": "nexus-staffplusplus-mirror", "name": "nexus-staffplusplus", "mirrorOf": "external:http:*", "url": "http://staffplusplus.org:8081/repository/staffplusplus"}]'
            -   name: Build with Maven
                run: mvn -B package --file pom.xml

    backwards_merge:
        if: ${{ github.event_name != 'pull_request' }}
        needs: build
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Declare some variables
                id: vars
                shell: bash
                run: |
                    echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
                    echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

            -   name: Commit files
                shell: bash
                env:
                    COMMIT_HASH: ${{ steps.vars.outputs.sha_short }}
                    GITHUB_TOKEN: ${{ secrets.PAT_STAFF }}
                run: |
                    set -e
                    declare -a VERSIONS=(
                      1.17.0
                      1.16.0
                      1.15.0
                      1.14.0
                      1.13.0
                      1.12.0
                    )
                    git clone https://garagepoort:${GITHUB_TOKEN}@github.com/garagepoort/StaffPlusPlus.git
                    cd StaffPlusPlus

                    git config --local user.email "action@github.com"
                    git config --local user.name "GitHub Action"
                    parents=$(git show --no-patch --format="%P" $COMMIT_HASH)
                    IFS=' ' read -ra arr <<<"$parents"
                    for i in "${VERSIONS[@]}"; do
                      RELEASE_BRANCH="release/$i"
                      git checkout $RELEASE_BRANCH
                      git pull
                      if [ ${#arr[@]} -gt 1 ]
                      then
                        git cherry-pick -m 1 $COMMIT_HASH
                        echo "Merge commit"
                      else
                        echo "Normal commit"
                        git cherry-pick $COMMIT_HASH
                      fi
                      git push
                    done
