# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Release_1.17.0

on:
  push:
    branches: [ release/1.17.0 ]
  pull_request:
    branches: [ release/1.17.0 ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.16
      uses: actions/setup-java@v1
      with:
        java-version: 1.16
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
              ${{ runner.os }}-maven-
    - name: Build with Maven
      run: mvn -B clean verify --file pom.xml
